apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
    name: cluster-test
    region: eu-west-1
vpc:
  id: "vpc-0e92dc51e4d811cff"  # (optional, must match VPC ID used for each subnet below)
  cidr: "10.0.0.0/16"       # (optional, must match CIDR used by the given VPC)
  subnets:
    # must provide 'private' and/or 'public' subnets by availibility zone as shown
    public:
      eu-west-1b:
        id: "subnet-054f60be9793cdbf3"
        cidr: "10.0.5.0/24" # (optional, must match CIDR used by the given subnet)

      eu-west-1c:
        id: "subnet-087451219a0560176"
        cidr: "10.0.6.0/24"  # (optional, must match CIDR used by the given subnet)

      eu-west-1a:
        id: "subnet-093014c534fdcec11"
        cidr: "10.0.4.0/24"   # (optional, must match CIDR used by the given subnet)
    private:
      eu-west-1a:
        id: "subnet-02fd5630cafb10ff9"
        cidr: "10.0.1.0/24"
        
      eu-west-1b:
        id: "subnet-09d26827f6c04fb46"
        cidr: "10.0.2.0/24" 

      eu-west-1c:
        id: "subnet-0c44eb48f376d8eb3"
        cidr: "10.0.3.0/24" 
nodeGroups:
    - name: ng-1
      minSize: 2
      maxSize: 3
      instancesDistribution:
        maxPrice: 0.017
        instanceTypes: ["t3.small", "t3.medium"] # At least one instance type should be specified
        onDemandBaseCapacity: 0
        onDemandPercentageAboveBaseCapacity: 50
        spotInstancePools: 2